### ISSUE TITLE
output the list of stages (pending PRs) so that the jenkins plugin can update the jenkins steps/stages

### ISSUE THREAD

**Issue by jstrachan** [fabric8io/updatebot#9]
the jenkins `updatebotPush()` step will need to keep running the `updatebot push` CLI periodically to find a list of PRs generated and their status (while also auto-closing or rebasing them).

So we should generate some output file that the jenkins plugin can read at some canonical file location.

e.g. 

```
updatebot push --output status.yml --tag 1.2.3 https://github.com/foo/bar.git
```
then the generated `status.yml` file that gets generated could look something like

```yaml
- name: PR on jstrachan-testing/ngx-widgets
   url: https://github.com/jstrachan-testing/ngx-widgets/pull/13
   status: MERGED
- name: PR on foo/bar
   url: https://github.com/jstrachan-testing/ngx-login/pull/13
   status: FAILED
```
